/*
path: layout.tsx
completePath: >-
  /Users/gastongorosterrazu/Aptugo/BaseDev/templates/Bootstrap/front-end/src/app/layout.tsx
keyPath: front-end/src/app/layout.tsx
unique_id: cwAdqyFT
*/

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          {children}
        </div>
      </body>
    </html>
  )
}
