/*
path: edit.tpl
keyPath: elements/Fields/UUID/edit.tpl
unique_id: CpTsFGvq
*/
{% set tableName = ( field | fieldData ).table.name | friendly %}
{% set bpr %}
import TextField from '@mui/material/TextField'
{% endset %}
{{ save_delayed('bpr', bpr) }}
{ {{ tableName }}data.{{ field.column_name | friendly }}
    ? <TextField
        {% if element.values.DisableUnderline %}
            InputProps={ { disableUnderline: true } }
        {% endif %}
        {% if element.values.Autofocus %}autoFocus{% endif %}
        {% if element.values.DisableVariable %}disabled={ {{ element.values.DisableVariable }} }{% endif %}
        {% if field.placeholder %}placeholder={{ field.placeholder | textOrVariable }}{% endif %}
        margin='{{ element.values.margin|default("dense") }}'
        label={{ field.prompt|default(field.column_name)  | textOrVariable }}
        className={ {% if element.values.classname %}{{ element.values.classname }}{% else %}'field_{{ field.column_name | friendly }}'{% endif %}}
        type="text"
        disabled
        fullWidth
        variant="{{ element.values.variant|default('standard') }}"
        value={ {{ tableName }}data.{{ field.column_name | friendly }} || '' }
        onChange={handle{{ tableName }}Change("{{ field.column_name | friendly }}")}
    />
    : <div>Autogenerated UUIDD</div>
}
